name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup directory
        run: |
          mkdir -p dist
          ls -la

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Rushhaabhhh 
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Verify Output
        run: |
          ls -la dist/
          
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🐍 Generate Snake Animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
