name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Directory
        run: |
          mkdir -p dist
          
      - name: Generate Pacman Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Rushhaabhhh
          outputs: |
            dist/github-contribution-grid-pacman.svg
          
          # Custom SVG output configuration
          gif_out_path: dist/github-contribution-grid-pacman.gif
          svg_out_path: dist/github-contribution-grid-pacman.svg
          snake_color: '#FFFF00'
          animation_speed: 20
          snake_size: 2
          
          # Combined CSS for Pacman and fireworks effects
          css: |
            :root {
              --grid-size: 12px;
              --color-snake: #FFFF00;
              --color-food: #00FF00;
              --grid-cell-size: 16px;
            }
            
            .contribution-grid {
              position: relative;
              overflow: hidden;
            }
            
            .contribution-grid rect {
              transition: fill 0.5s;
            }
            
            .snake {
              animation: chomp 0.4s linear infinite;
            }
            
            @keyframes chomp {
              0% { clip-path: circle(50%); }
              50% { clip-path: polygon(100% 0, 50% 50%, 100% 100%, 0 100%, 0 0); }
              100% { clip-path: circle(50%); }
            }
            
            .food.eaten {
              animation: explode 0.5s ease-out;
            }
            
            @keyframes explode {
              0% { transform: scale(1); opacity: 1; }
              50% { transform: scale(2); opacity: 0.5; }
              100% { transform: scale(0); opacity: 0; }
            }
            
            .firework-container {
              position: absolute;
              top: 0;
              left: 0;
              width: 100%;
              height: 100%;
              pointer-events: none;
            }
            
            .firework {
              position: absolute;
              width: 5px;
              height: 5px;
              border-radius: 50%;
              animation: firework 1s ease-out;
              opacity: 0;
            }
            
            @keyframes firework {
              0% { transform: scale(0); opacity: 1; }
              50% { transform: scale(1); opacity: 0.8; }
              100% { transform: scale(2); opacity: 0; }
            }
            
            .eaten-dot {
              animation: pulse 0.5s ease-out;
            }
            
            @keyframes pulse {
              0% {
                transform: scale(1);
                opacity: 1;
              }
              50% {
                transform: scale(1.5);
                opacity: 0.7;
              }
              100% {
                transform: scale(0);
                opacity: 0;
              }
            }
            
            .pacman {
              animation: eat 0.4s linear infinite;
            }
            
            @keyframes eat {
              0% { transform: rotate(0deg); }
              50% { transform: rotate(45deg); }
              100% { transform: rotate(0deg); }
            }
      
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🎮 Generate Pacman Animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
