name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
@@ -30,19 +29,26 @@ jobs:
          outputs: |
            dist/github-contribution-grid-pacman.svg
          
          # Configuration for Pacman and gameplay elements
          color_snake: '#FFFF00'
          color_dots: '#2196f3'
          
          outputs_full: |
            dist/github-contribution-grid-pacman.svg {
              color_snake: "#FFFF00",
              color_dots: "#2196f3",
              color_sausage: "#FFFF00",
              radius: 2,
              frame_duration: 160,
              transform_speed_ratio: 0.5
            }
          
          # Combined CSS for Pacman and fireworks effects
          css: |
            :root {
              --grid-size: 12px;
              --color-snake: #FFFF00;
              --color-food: #2196f3;
              --grid-cell-size: 16px;
            }
            
@@ -51,11 +57,9 @@ jobs:
              overflow: hidden;
            }
            
            /* Pacman Animation */
            .snake {
              fill: var(--color-snake);
              animation: chomp 0.4s linear infinite;
            }
            
@@ -65,8 +69,14 @@ jobs:
              100% { clip-path: circle(50%); }
            }
            
            /* Dots and Food Animation */
            .food {
              fill: var(--color-food);
              transition: transform 0.3s ease-out;
            }
            
            .food.eaten {
              animation: explode 0.5s ease-out forwards;
            }
            
            @keyframes explode {
@@ -75,57 +85,62 @@ jobs:
              100% { transform: scale(0); opacity: 0; }
            }
            
            /* Fireworks Animation */
            .firework {
              position: absolute;
              width: 4px;
              height: 4px;
              background: radial-gradient(circle, #ff0 0%, #ff0 30%, transparent 70%);
              border-radius: 50%;
              animation: firework 1s ease-out forwards;
            }
            
            @keyframes firework {
              0% {
                transform: translate(var(--x), var(--y)) scale(0);
                opacity: 1;
              }
              50% {
                transform: translate(
                  calc(var(--x) + var(--vx) * 50px),
                  calc(var(--y) + var(--vy) * 50px - 25px)
                ) scale(1);
                opacity: 0.8;
              }
              100% {
                transform: translate(
                  calc(var(--x) + var(--vx) * 100px),
                  calc(var(--y) + var(--vy) * 100px)
                ) scale(2);
                opacity: 0;
              }
            }
            
            /* Score Animation */
            .score-popup {
              position: absolute;
              font-family: 'Press Start 2P', cursive;
              color: #FFD700;
              font-size: 12px;
              pointer-events: none;
              animation: scoreFloat 1s ease-out forwards;
            }
            
            @keyframes scoreFloat {
              0% { transform: translateY(0); opacity: 1; }
              100% { transform: translateY(-20px); opacity: 0; }
            }
            
            /* Power-up Animation */
            .power-up {
              fill: #FFD700;
              animation: pulse 1s infinite;
            }
            
            @keyframes pulse {
              0% { transform: scale(1); }
              50% { transform: scale(1.2); }
              100% { transform: scale(1); }
            }
      
      - name: Push to GitHub Pages
